env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  main: main.go
brews:
  - description: "security-hub-collector is a tool for pulling AWS Security Hub findings for visualization."
    tap:
      owner: trussworks
      name: homebrew-tap
    homepage: "https://github.com/trussworks/security-hub-collector"
    commit_author:
      name: trussworks-infra
      email: infra+github@truss.works
dockers:
  -
    ids:
      - security-hub-collector
    image_templates:
      - "trussworks/security-hub-collector:{{ .Tag }}"
    skip_push: true
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
