name: build-and-push-dev

on:
  push:
    # this value should match any deployment branches configured for the target GitHub environment for https://github.com/CMSgov/security-hub-collector
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-branches
    # branches: [main]  
    branches: bharvey-collector # TODO REVERT

jobs:
  build:
    uses: ./.github/workflows/reusable-build-and-push.yml
    with:
      environment: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
