name: Generate code.json
on:
  schedule:
   - cron: "0 0 1 * *" # monthly

jobs:
  update-code-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Generate token from GitHub App
        id: create_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.PR_PERMS_APP_ID }}
          private-key: ${{ secrets.PR_PERMS_APP_SECRET }}
          owner: Enterprise-CMCS

      - name: Update code.json
        uses: DSACMS/automated-codejson-generator@v1.0.0
        with:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          BRANCH: "main"
